### ISSUE TITLE
Add gray background color when hovering UserItem in /messages

### ISSUE THREAD

**Issue by ktsu2i** [ktsu2i/utopia#122]
As you see a list of users in `/message`, even if you hover each user, you do not really see if you are really hovering it.

TODO:
- Add background color when hovering `UserItem` in `/messages`
- Use `bg-gray-50` for the color

**Comment by sumana0406** [comment]
![image](https://github.com/user-attachments/assets/0e4646e3-c969-4deb-b704-08b3d315bf30)
Shows up bg-gray-50 when the cursor is hovered over the user's dm d
